### ISSUE TITLE
Decide between UI variations

### ISSUE THREAD

**Issue by victorreisenauer** [RealEst-AI/ImmoMail-Outlook-Addin#67]
We need to decide whether we can do "big screen" UI or stick to "side screen" UI or if both are possible (within the same plugin).

**Comment by Wladefant** [comment]
we have decided to not pursue the path of module extensions, because they do not make sense at all, too much code reimplementation and they have no purpose to have instead of creating its own platform

Here are some of my notes for the following topic:

Module Extensions:
https://cwviqqfjgz.joplinusercontent.com/shares/D8IufmUIGnpt3QaSboWUgr
[https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/extension-module-outlook-add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/extension-module-outlook-add-ins)

Those are full page plugins, Mailbox and context is not supported, the graph api is supported, 


[**Registering Mailbox and Item events is not available with this extension point.**](Registering Mailbox and Item events is not available with this extension point.)

That means no emails can be opened in new window



### Teams Personal Tab
https://cwviqqfjgz.joplinusercontent.com/shares/EQsx31u5MmXQWtA1ndmmkN

# Better alternative: Teams personal tab
Supported platforms: Teams desktop, mobile, Teams web, Microsoft 365 web, Microsoft 365 desktop, Microsoft 365 mobile, Outlook desktop, Outlook web, Outlook mobile

No support for Mailbox and Item events, which means no new window email ecetera
## Documentation	
[Extend a Teams personal tab across Microsoft 365](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit)
[Teams JavaScript client library](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#microsoft-365-support-running-teams-apps-in-microsoft-365-and-outlook)
[Publish Teams apps for Microsoft 365](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/publish)
## Samples
[https://github.com/OfficeDev/m365-extensibility-image-editor?tab=readme-ov-file](https://github.com/OfficeDev/m365-extensibility-image-editor?tab=readme-ov-file)

![demo.gif](:/d19d9ec3bcab4134aa20525830289545)

[Editable todo list with SSO built with React and Azure Functions. Works in Teams, Outlook, Microsoft 365 app.](https://github.com/OfficeDev/teams-toolkit-samples/tree/v2.1.0/todo-list-with-Azure-backend-M365)




![todo-list-M365.gif](:/ffc9bd9878224ea9afe511301942578f)

**Comment by Wladefant** [comment]
My clear proposal and next step would be to have a seperate platform for that clearly more people are needed
